export const digestConfig = {
  defaultLanguage: 'en',

  chart: {
    width: 800,
    height: 400,
    backgroundColor: 'rgba(75, 192, 192, 0.6)',
    title: 'Weekly Fleet Deliveries',
    barLabel: 'Deliveries',
    locale: 'en-US',
  },

  chartImagePath: '/weekly-digest-chart.png',

  statEmojis: {
    block: '🚫',
    caution: '⚠️',
    none: '✅',
  },

  regionBadges: {
    East: '🧭',
    West: '🌅',
    North: '❄️',
    South: '🌴',
    Central: '🏙️',
  },

  regions: {
    East: { color: '#2D9CDB', label: 'East Zone' },
    West: { color: '#F2994A', label: 'West Frontier' },
    North: { color: '#27AE60', label: 'Northern District' },
    South: { color: '#9B51E0', label: 'Southern Belt' },
    Central: { color: '#EB5757', label: 'Central Hub' },
  },

  locales: {
    en: {
      improvedTitle: '🎉 Drivers Who Improved:',
      noImprovements: '💤 No driver flag recoveries this week.',
      footer: '_Generated by FLEETOS Digest Engine_',
    },
    fr: {
      improvedTitle: '🎉 Conducteurs améliorés :',
      noImprovements: '💤 Aucun changement cette semaine.',
      footer: '_Généré par FLEETOS Digest Engine_',
    },
    sw: {
      improvedTitle: '🎉 Madereva Walioimarika:',
      noImprovements: '💤 Hakuna mabadiliko wiki hii.',
      footer: '_Imetengenezwa na FLEETOS Digest Engine_',
    },
  },
};