      - name: Install Axios
        run: npm install axios

      - name: Comment Lighthouse scores on PR
        if: github.event_name == 'pull_request'
        run: node .github/scripts/post-lhci-comment.js ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}